apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: go-app-gg
  namespace: default
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: go-app-gg
spec:
  source:
    git:
      url: https://github.com/aci-adr/go-app-gg
      ref:
        branch: main
